# Galformer ROI Analysis Configuration File

# Experiment configuration
experiment:
  name: 'galformer_btc_roi_analysis'
  description: 'ROI analysis on full BTC dataset'

# Data preprocessing
data:
  filename: 'Datasets/btc_daily_last_3000_days.csv' # BTC-USD.csv
  division_rate1: 0.8  # train/validation split (no training data needed)
  division_rate2: 0.9  # validation/test split (use entire dataset for testing)
  normalize: true

# Model architecture
model:
  d_model: 512
  dense_dim: 2048
  num_features: 1
  num_heads: 8
  num_layers: 6
  dropout_rate: 0.1
  
# Sequence lengths
sequence:
  src_len: 20      # encoder input sequence length
  dec_len: 1       # decoder input sequence length  
  tgt_len: 1       # target sequence length (predict 1 day ahead)
  window_size: 20  # same as src_len
  mulpr_len: 1     # same as tgt_len (predict 1 day ahead)

# Training parameters (not used for ROI analysis)
training:
  batch_size: 32
  epochs: 100
  learning_rate: 0.0001
  min_learning_rate: 0.00001

# Learning rate scheduler (not used for ROI analysis)
scheduler:
  T_i: 10
  T_mult: 2
  T_cur: 0

# Noise testing configuration
noise_test:
  enabled: false
  noise_level: 1.0  # percentage of price volatility to add as noise

# Output paths (will be prefixed with runs/{experiment.name}/)
output:
  model_path: 'galformer_model.pth'
  predictions_path: 'Galformer_predictions.csv'
  plot_path: 'Galformer_predictions.png'
