# Galformer Configuration File

# Experiment configuration
experiment:
  name: 'galformer_btc_1day_prediction-20250918-v3-6'
  description: 'Galformer model predicting BTC prices 1 day ahead'

# Data preprocessing
data:
  filename: 'Datasets/btc_daily_last_3000_days.csv'
  division_rate1: 0.8  # train/validation split
  division_rate2: 0.9  # validation/test split

# Model architecture
model:
  d_model: 512
  dense_dim: 2048
  num_features: 1
  num_heads: 8
  num_layers: 6
  dropout_rate: 0.1
  
# Sequence lengths
sequence:
  src_len: 20      # encoder input sequence length
  dec_len: 1       # decoder input sequence length  
  tgt_len: 1       # target sequence length (predict 1 day ahead)
  window_size: 20  # same as src_len
  mulpr_len: 1     # same as tgt_len (predict 1 day ahead)

# Training parameters
training:
  epochs: 200
  batch_size: 64
  learning_rate: 0.003
  min_learning_rate: 7e-11
  load_model_path: "runs/galformer_btc_1day_prediction-20250915-v3-5/galformer_model.pth"  # Set to path of saved model to load instead of training from scratch
  skip_training: true # Set to true to skip training and only run inference

# Learning rate scheduler
scheduler:
  T_i: 1
  T_mult: 2
  T_cur: 0.0

# Output paths (will be prefixed with runs/{experiment.name}/)
output:
  model_path: 'galformer_model.pth'
  predictions_path: 'Galformer_predictions.csv'
  plot_path: 'Galformer_predictions.png'
